#!/usr/bin/env bash

tmpbg='/tmp/screen.png'

# take a screenshot
maim "$tmpbg"

# blur the screenshot by resizing and scaling back up
convert "$tmpbg" -filter Gaussian -thumbnail 20% -sample 500% "$tmpbg"

# overlay the icon onto the screenshot
convert "$tmpbg" -gravity center -composite "$tmpbg"

# lock the screen with the blurred screenshot
xss-lock -- i3lock -n -i "$tmpbg" &
