#!/bin/sh -e

dir="$HOME/.config/rofi/launchers/type-4"
theme='style-1'
emoji=$(cat "$HOME/.config/menu/emoji.txt" | rofi -dmenu -theme ${dir}/${theme}.rasi -p | sed 's/ .*//')

if [ -z "$emoji" ]; then
    exit
fi

# if XDG_CURRENT_DESKTOP is x11, then use xclip
# else use wl-copy
#
#
if [ "$XDG_CURRENT_DESKTOP" = "x11" ]; then
		printf "$emoji" | xclip -sel clipboard
else
		printf "$emoji" | wl-copy
fi
echo "Copied $emoji to clipboard!"
